# The Python Programming Language Data Types
### Dates and Times

In [1]:
import datetime as dt
import time as tm

In [2]:
#Current time since Epoch
#https://en.wikipedia.org/wiki/Year_2038_problem
tm.time()

1605832271.592879

In [3]:
#convert
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 11, 20, 8, 31, 11, 605181)

In [4]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2020, 11, 20, 8, 31, 11)

`timedelta` is a duration expressing the difference between two dates.

# Objects and Maps

In [5]:
class Person:
    department = 'UChicago Graham School' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [6]:
person = Person()
person.set_name('Your name.....')
person.set_location('Chicago, IL, USA')
print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))

Your name..... lives in Chicago, IL, USA and works in the department UChicago Graham School


In [7]:
class SomeClass:
    variable_1 = "This is a class variable"
    variable_2 = 100   #this is also a class variable

In [8]:
class SomeClass:
    variable_1 = "This is a class variable"
    variable_2 = 100    #this is also a class variable.

    def __init__(self, param1, param2):
        self.instance_var1 = param1
        #instance_var1 is a instance variable
        self.instance_var2 = param2   
        #instance_var2 is a instance variable

In [9]:
obj1 = SomeClass("first paramater", 18) 
#creating instance of SomeClass named obj1
obj2 = SomeClass(28, 6) 
#creating a instance of SomeClass named obj2

obj2.instance_var1


#obj2.variable_1

28

In [10]:
class SomeClass:    
    def create_arr(self): # An instance method
        self.arr = []
    
    def insert_to_arr(self, value):  #An instance method
        self.arr.append(value)

In [11]:
obj3 = SomeClass()
obj3.create_arr()
obj3.insert_to_arr(5)
obj3.arr

[5]

In [12]:
class SomeClass:
    def create_arr(self): # An instance method
        self.arr = []
    
    def insert_to_arr(self, value):  #An instance method
        self.arr.append(value)
        
    @classmethod
    def class_method(cls):
        print("the class method was called")

In [13]:
SomeClass.class_method()

the class method was called


In [14]:
class MyClass:
    def method(self):
        return 'instance method called', self

    @classmethod
    def classmethod(cls):
        return 'class method called', cls

    @staticmethod
    def staticmethod():
        return 'static method called'

## Source:https://realpython.com/instance-class-and-static-methods-demystified/#:~:text=Instance%20methods%20need%20a%20class,the%20class%20itself%20via%20cls%20.&text=They%20work%20like%20regular%20functions%20but%20belong%20to%20the%20class's%20namespace.


### Instance Methods
The first method on MyClass, called method, is a regular instance method. That’s the basic, no-frills method type you’ll use most of the time. You can see the method takes one parameter, self, which points to an instance of MyClass when the method is called (but of course instance methods can accept more than just one parameter).

Through the self parameter, instance methods can freely access attributes and other methods on the same object. This gives them a lot of power when it comes to modifying an object’s state.

Not only can they modify object state, instance methods can also access the class itself through the self.__class__ attribute. This means instance methods can also modify class state.

### Class Methods
Let’s compare that to the second method, MyClass.classmethod. I marked this method with a @classmethod decorator to flag it as a class method.

Instead of accepting a self parameter, class methods take a cls parameter that points to the class—and not the object instance—when the method is called.

Because the class method only has access to this cls argument, it can’t modify object instance state. That would require access to self. However, class methods can still modify class state that applies across all instances of the class.

### Static Methods
The third method, MyClass.staticmethod was marked with a @staticmethod decorator to flag it as a static method.

This type of method takes neither a self nor a cls parameter (but of course it’s free to accept an arbitrary number of other parameters).

Therefore a static method can neither modify object state nor class state. Static methods are restricted in what data they can access - and they’re primarily a way to namespace your methods.



In [15]:
obj = MyClass()

In [16]:
obj.method()

('instance method called', <__main__.MyClass at 0x7faf95068ac0>)

In [17]:
obj.classmethod()

('class method called', __main__.MyClass)

In [18]:
'''
method (the instance method) has access to the object instance (printed as <MyClass instance>) via the self argument.

When the method is called, Python replaces the self argument with the instance object, obj. 
We could ignore the syntactic sugar of the dot-call syntax (obj.method()) 
and pass the instance object manually to get the same result:
'''
MyClass.method(obj)

('instance method called', <__main__.MyClass at 0x7faf95068ac0>)

##### refer: https://docs.python.org/3/tutorial/classes.html
Classes provide a means of bundling data and functionality together. Creating a new class creates a new type of object, allowing new instances of that type to be made. Each class instance can have attributes attached to it for maintaining its state. Class instances can also have methods (defined by its class) for modifying its state.

Unlike some other languages, when a new object is created in python, it does not create a new set of instance methods to itself. So instance methods lie within the class object without being created with each object initialization — nice way to save up memory. Recall that python is a fully object oriented language and so a class is also an object. So it lives within the memory

In [19]:
#map min function between two lists
store1 = [10.00, 11.00, 12.31, 2.34]
store2 = [9.00, 11.10, 12.32, 2.01]
cheapest = map(min, store1, store2)

#iterate over the map object 
for item in cheapest:
    print(item)

9.0
11.0
12.31
2.01


Note: Python sequence slice addresses can be written as a[start:end:step] and any of start, stop or end can be dropped.  a[::3] is every third element of the sequence.

In [20]:
people = ['Dr. Utku Pamuksuz', 'Dr. Greg Green', 'Dr. Yuri Balasanov', 'Dr. Eric Larson']

def split_title_and_name(person):
    return #your code is here

list(map #your code is here)

SyntaxError: unexpected EOF while parsing (<ipython-input-20-5377feae1b9a>, line 6)

# Lambda and List Comprehension

The list comprehension starts with a '[' and ']', to help you remember that the
result is going to be a list.

The basic syntax is

##### [ expression for item in list if conditional ]



This is equal to: 
for item in list:
    if conditional:
        expression
        
        
        
###### new_list = [expression(i) for i in old_list if filter(i)]

new_list    
The new list (result).

expression(i)
Expression is based on the variable used for each element in the old list.

for i in old_list
The word for followed by the variable name to use, followed by the word in the
old list.

if filter(i)
Apply a filter with an If-statement.

In [ ]:
new_range  = [i * i for i in range(5)   if i % 2 == 0]
'''
Which corresponds to:

*result*  = [*transform*    *iteration*         *filter*     ]

The * operator is used to repeat. The filter part answers the question if the
item should be transformed. 
'''

In [ ]:
# Lets list even numbers between 0-1000
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list[:4]

In [ ]:
#https://blog.teamtreehouse.com/python-single-line-loops 

In [ ]:
numbers = [1, 2, 3, 4]
squares = []

for n in numbers:
  squares.append(n**2)

print(squares) 

In [ ]:
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

common_num = []

for a in list_a:
  for b in list_b:
    if a == b:
      common_num.append(a)
      
print(common_num)

### LAMBDA
lambda operator or lambda function is used for creating small, one-time and anonymous function objects in Python.




##### lambda arguments : expression


lambda operator can have any number of arguments, but it can have only one expression. It cannot contain any statements and it returns a function object which can be assigned to any variable.

In [ ]:
 def add(x, y): 
    return x + y
  
# Call the function
add(2, 3)

In [ ]:
add = lambda x, y : x + y 
  
print (add(2, 3))

In lambda x, y: x + y; x and y are arguments to the function and x + y is the expression which gets executed and its values is returned as output.

lambda x, y: x + y returns a function object which can be assigned to any variable, in this case function object is assigned to the add variable.

type(add)

Mostly lambda functions are passed as parameters to a function which expects a function objects as parameter like map, reduce, filter functions

#### MAP
map(function_object, iterable1, iterable2,...)


In [ ]:
def multiply2(x):
    return x*2
    
a=map(multiply2,[1, 2, 3, 4])
list(a)

In [ ]:
a=map(lambda x : x*2, [1, 2, 3, 4]) 
list(a)

In [ ]:
Celsius = [39.2, 36.5, 37.3, 37.8]
#your map lambda code here

### Numerical Python (NumPy)

In [21]:
import numpy as np
#create a list and convert to np array
mylist = [1, 2, 3]
x = np.array(mylist)

In [22]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [23]:
# pass a list of lists to create a multidimensional array
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [24]:
# use the shape method to find dimensions of an array
m.shape

(2, 3)

In [25]:
n = np.arange(0, 30, 2)

In [26]:
np.zeros(4) #look at np.zeros and np.ones
#https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html

array([0., 0., 0., 0.])

In [27]:
print (x+y) #(x-y),(x/y),(x*y),(x**2)

[5 7 9]


In [28]:
z = np.array([3, 6, 9, 12])

print(z/4)

[0.75 1.5  2.25 3.  ]


In [29]:
y = [3, 6, 9, 12]
print (y/3)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
#z.sum() #z.max(),z.mean(),z.std()

z.argmin()#return the index value in array

In [ ]:
z.mean()

In [ ]:
np.amin(z)

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

In [ ]:
r[2,2]
r[2,3:6]

In [ ]:
r[r>30]

In [ ]:
r[r>30]=30
r

In [ ]:
test = np.random.randint(0, 10, (4,3))
test

In [ ]:
test[2]

In [ ]:
#iterate by row
for row in test:
    print(row)

In [ ]:
#iterate by index
for i in range(len(test)):
    print(test[i])

In [ ]:
#iterate by row and index
for i, row in enumerate(test):
    print('row', i, 'is', row)

In [ ]:
test2 = test**2
test2

In [ ]:
#iterate over multiple iterables
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

# Series

In [ ]:
import pandas as pd
pd.Series?

In [ ]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [ ]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])


In [ ]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

In [ ]:
s.iloc[1]
s.loc['Golf']
s[1]
s['Golf']

In [ ]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

In [ ]:
total = 0
for item in s:
    total+=item
print(total)

In [ ]:
import numpy as np

total = np.sum(s)
print(total)

In [ ]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()
len(s)

In [ ]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

In [ ]:
%%timeit -n 100
summary = np.sum(s)

In [ ]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'India',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [ ]:
all_countries
all_countries.loc['Cricket']
all_countries['Cricket']

# DataFrame as Data Structure

In [ ]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'David',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Brandon',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vivek',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

In [ ]:
df.loc['Store 2']

In [ ]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

In [ ]:
df = pd.read_csv('olympics.csv')
df.head()

In [ ]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

In [ ]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head()

In [ ]:
df = pd.read_csv('census.csv')
df.head()

In [ ]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [ ]:
df = pd.read_csv('log.csv')
df

In [ ]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [ ]:
df = df.fillna(method='ffill')
df.head()